### PR TITLE
Fixed using activeName to set initial displayed tab. Updated tests to…

### PR DESCRIPTION
**Pull request by cah-brian-gantzler**
… more modern ember syntax

### CODE REVIEW

**Comment by rajasegar** [comment]
@cah-brian-gantzler There are some lint failures in the CI, can you please fix them?

**Comment by cah-brian-gantzler** [comment]
completed

**Review by rajasegar — APPROVED** [review]

**Comment by cah-brian-gantzler** [comment]
While you approved it, you will have to merge it, there is not a button for me to do it

**Comment by rajasegar** [comment]
@cah-brian-gantzler I have sent you a collaborator request, please check your inbox.
Once you become one, I think you don't have to wait for me.

**Comment by cah-brian-gantzler** [comment]
I think that a release should be made with this fix. The V2 version should prob bump a major version number. Not sure how you do releases

**Pull request merged**
